### PR TITLE
fix(usage): use latest version of lodash.difference

### LINKED ISSUE #32: TypeError: predicate is not a function
Not sure if it's really `eslint-find-new-rules` the culprit here but it looks like it is according to the stack trace:

```
.../eslint-config-i-am-meticulous/node_modules/lodash.difference/node_modules/lodash._baseflatten/index.js:73
    if (depth > 0 && predicate(value)) {
                     ^

TypeError: predicate is not a function
    at baseFlatten (.../eslint-config-i-am-meticulous/node_modules/lodash.difference/node_modules/lodash._baseflatten/index.js:73:22)
    at .../eslint-config-i-am-meticulous/node_modules/lodash.difference/index.js:73:29
    at .../eslint-config-i-am-meticulous/node_modules/lodash.rest/index.js:112:27
    at findNewRules (.../eslint-config-i-am-meticulous/node_modules/eslint-find-new-rules/index.js:17:10)
    at Object.<anonymous> (.../eslint-config-i-am-meticulous/node_modules/eslint-find-new-rules/bin.js:14:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
.../eslint-config-i-am-meticulous/node_modules/npmpub/npmpub.js:204
        throw err
        ^

Error: 'npm test' failed.
    at .../eslint-config-i-am-meticulous/node_modules/npmpub/npmpub.js:157:15
```

Any idea?

### PR DESCRIPTION
**Pull request by sarbbottam**
fix #32

### CODE REVIEW

**Comment by sarbbottam** [comment]
verified the fix.

```
cd somedir
git clone git@github.com:MoOx/eslint-config-i-am-meticulous.git
git clone git@github.com:kentcdodds/eslint-find-new-rules.git
cd eslint-config-i-am-meticulous.git
# edit eslint-config-i-am-meticulous.git/package.json
```

``` diff
   "devDependencies": {
     "babel-eslint": "^6.0.0-beta.6",
     "eslint": "^2.0.0",
-    "eslint-find-new-rules": "^1.2.0",
+    "eslint-find-new-rules": "../eslint-find-new-rules",
     "eslint-plugin-ava": "^1.3.0",
     "eslint-plugin-flow-vars": "^0.2.1",
     "eslint-plugin-react": "^4.2.3",
```

```
npm i
npm run check-update
...
New rules to add to the config: react/require-render-return.
...
```

**Comment by sarbbottam** [comment]
@kentcdodds @ta2edchimp could you please review?

cc/ @MoOx

**Comment by kentcdodds** [comment]
Sweet! Thanks. Releasing now!

celebrate-DKnMqdm9i980E

**Comment by sarbbottam** [comment]
Fix landed in [`2.0.1`](https://www.npmjs.com/package/eslint-find-new-rules)

**Pull request merged**
