### PR TITLE
Use proxyquire to mock fs object ...

### PR DESCRIPTION
**Pull request by ta2edchimp**
instead of using `mock-fs`.

This should fix the issue shown in #6

### CODE REVIEW

**Comment by kentcdodds** [comment]
Huh... I wonder why this didn't kick off a travis build... I'll pull it down locally and give it a look. Thanks!

**Comment by ta2edchimp** [comment]
I think travis only kicks in on PRs to the `master` branch, I compared against and created the PR towards your `ava-bug` branch.

**Comment by kentcdodds** [comment]
Ah! That makes sense. Do you mind making this same PR to master? I haven't had a chance to pull it down yet. Thanks :+1:

**Comment by ta2edchimp** [comment]
See #8.

Strange, this pr got its checks through travis now...

**Pull request closed without merging**
