### PR TITLE
test(tests): test for bin.js

### LINKED ISSUE #2: Test `bin.js`
Shouldn't be too much work...

### PR DESCRIPTION
**Pull request by sarbbottam**
Closes #2 

screen shot 2016-03-17 at 8 13 21 pm

@kentcdodds please review

### CODE REVIEW

**Comment by kentcdodds** [comment]
Couldn't have done it better myself! Thanks @sarbbottam! @ta2edchimp, could you sign off on this too and press the green button if you're good with it?

**Comment by kentcdodds** [comment]
Oh, actually could you update your commit message? Change this from the `fix` type to a `test`? There's no reason to do a release with these changes I think :+1: Thanks!

**Comment by sarbbottam** [comment]
[Didn't know much about semantic release and the interactive prompt](https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-automating-releases-with-semantic-release), have been hand typing so far, will use `npm run commit` henceforth. :tada:

**Comment by kentcdodds** [comment]
Fantastic! This looks great. I'm assuming @ta2edchimp is sleeping so when he gets the chance to give this a look, I think we can get this merged :-)

**Comment by sarbbottam** [comment]
improved the code and assertion a bit ...

**Comment by ta2edchimp** [comment]
Looks good!

**Pull request merged**
